"""Add stored_files table for BLOB storage

Revision ID: b5d1d17df847
Revises:
Create Date: 2025-07-03 18:38:13.402944

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b5d1d17df847"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
